use super::*;
use crate::config::{MAX_CONFIGURED_NETWORKS, MAX_NETWORK_RPC_URLS, validate_config};
use std::collections::{BTreeMap, BTreeSet};

/// The vendored file is generated by a tool that talks to the network, so
/// nothing about it is checked by the compiler. This is the check: it runs in
/// CI, and a registry that would panic on a user's first launch fails here
/// instead.
#[test]
fn registry_is_well_formed() {
    let profiles = parse(EMBEDDED).expect("the vendored registry parses and validates");
    assert!(
        profiles.len() > 500,
        "the registry holds only {} chains; the vendored file looks truncated",
        profiles.len()
    );
}

#[test]
fn registry_identifiers_are_unique_across_every_chain() {
    let mut chain_ids = BTreeSet::new();
    let mut identifiers = BTreeMap::new();
    for profile in known_networks() {
        assert!(
            chain_ids.insert(profile.config.chain_id),
            "chain {} appears twice",
            profile.config.chain_id
        );
        for identifier in std::iter::once(&profile.config.name).chain(&profile.config.aliases) {
            // Uniqueness is what makes `network add <name>` unambiguous, and
            // the registry is large enough that a collision would otherwise be
            // found by whichever user typed the shadowed name first.
            assert!(
                identifiers
                    .insert(identifier.clone(), profile.config.chain_id)
                    .is_none(),
                "{identifier} names both chain {} and chain {}",
                identifiers[identifier],
                profile.config.chain_id
            );
        }
    }
}

#[test]
fn every_endpoint_is_https_and_listed_once() {
    for profile in known_networks() {
        let mut seen = BTreeSet::new();
        for endpoint in &profile.config.rpc_urls {
            // Plaintext would let anything on the path rewrite a balance, a
            // simulation result, or the chain ID itself. The probe only ever
            // considers https, and this is the assertion that it stayed that
            // way through selection and vendoring.
            assert_eq!(
                endpoint.scheme(),
                "https",
                "chain {} lists a non-https endpoint {endpoint}",
                profile.config.chain_id
            );
            assert!(
                seen.insert(endpoint.as_str()),
                "chain {} lists {endpoint} twice, so it has fewer fallbacks than it appears to",
                profile.config.chain_id
            );
        }
        assert!(
            profile.config.rpc_urls.len() <= MAX_NETWORK_RPC_URLS,
            "chain {} lists more endpoints than a configuration accepts",
            profile.config.chain_id
        );
    }
}

/// The defaults have to be a configuration the wallet would accept from a
/// file, because that is exactly what they become on first run.
#[test]
fn defaults_form_a_valid_configuration() {
    let networks = default_networks();
    assert!(
        !networks.is_empty() && networks.len() <= MAX_CONFIGURED_NETWORKS,
        "{} default networks does not fit a configuration",
        networks.len()
    );
    validate_config(&crate::config::WalletConfig {
        version: 2,
        wallets: Vec::new(),
        networks,
    })
    .expect("the default networks validate as a configuration");
}

#[test]
fn only_the_four_primary_defaults_start_enabled() {
    let enabled = default_networks()
        .into_iter()
        .filter(|network| !network.disabled)
        .map(|network| network.name)
        .collect::<std::collections::BTreeSet<_>>();
    assert_eq!(
        enabled,
        ["arbitrum", "base", "ethereum", "robinhood"]
            .into_iter()
            .map(str::to_owned)
            .collect()
    );
}

#[test]
fn each_fresh_default_uses_exactly_the_highest_ranked_endpoint() {
    for network in default_networks() {
        let profile = known_network(network.chain_id).expect("default is in the registry");
        assert_eq!(
            network.rpc_urls.len(),
            1,
            "{} has multiple defaults",
            network.name
        );
        assert_eq!(network.rpc_urls[0], profile.config.rpc_urls[0]);
    }
}

#[test]
fn every_fresh_default_has_a_block_explorer() {
    for network in default_networks() {
        assert!(
            network.block_explorer_url.is_some(),
            "{} has no block explorer",
            network.name
        );
    }
}

#[test]
fn default_testnets_are_the_probed_project_operated_endpoints() {
    let expected = [
        (10200, "https://rpc.chiadochain.net/"),
        (46630, "https://rpc.testnet.chain.robinhood.com/"),
        (80069, "https://bepolia.rpc.berachain.com/"),
        (84532, "https://sepolia.base.org/"),
        (421_614, "https://sepolia-rollup.arbitrum.io/rpc"),
        (763_373, "https://rpc-gel-sepolia.inkonchain.com/"),
        (11_155_420, "https://sepolia.optimism.io/"),
    ];
    let defaults = known_networks()
        .iter()
        .filter(|profile| profile.is_default && profile.config.testnet)
        .map(|profile| {
            assert!(
                profile.simulate_endpoints > 0,
                "default testnet {} has no compatible simulation endpoint",
                profile.config.name
            );
            (
                profile.config.chain_id,
                profile.config.primary_rpc_url().as_str(),
            )
        })
        .collect::<Vec<_>>();
    assert_eq!(defaults, expected);
    assert!(
        default_networks()
            .iter()
            .filter(|network| network.testnet)
            .all(|network| network.disabled),
        "testnet defaults must never start enabled"
    );
}

/// Renaming a network breaks every script, alias, and habit that addresses
/// it, and the registry is regenerated by a tool that derives names from an
/// upstream registry it does not control. These are the names releases have
/// already handed out.
#[test]
fn established_networks_keep_their_names_and_aliases() {
    let expected: &[(u64, &str, &[&str])] = &[
        (1, "ethereum", &["mainnet", "eth"]),
        (10, "optimism", &["op", "op-mainnet"]),
        (100, "gnosis", &["gnosis-mainnet", "xdai"]),
        (143, "monad", &["monad-mainnet"]),
        (4326, "megaeth", &["megaeth-mainnet", "mega"]),
        (4663, "robinhood", &["robinhood-chain", "hood"]),
        (8453, "base", &["base-mainnet"]),
        (42161, "arbitrum", &["arbitrum-one", "arb", "arb1"]),
        (57073, "ink", &["ink-mainnet"]),
        (80094, "berachain", &["bera"]),
    ];
    for (chain_id, name, aliases) in expected {
        let profile = known_network(*chain_id)
            .unwrap_or_else(|| panic!("chain {chain_id} is missing from the registry"));
        assert_eq!(&profile.config.name, name, "chain {chain_id} was renamed");
        assert_eq!(
            profile.config.aliases, *aliases,
            "chain {chain_id} lost or gained an alias"
        );
        assert!(profile.is_default, "{name} stopped being a default network");
    }
}

/// Simulation is what gates signing, so the chains people are most likely to
/// use must have more than one endpoint that can do it. One is a single point
/// of failure wearing a list's clothing.
#[test]
fn the_busiest_chains_have_redundant_simulation() {
    for chain_id in [1_u64, 10, 8453, 42161, 100] {
        let profile = known_network(chain_id).expect("configured chain is in the registry");
        assert!(
            profile.simulate_endpoints >= 2,
            "chain {chain_id} has {} endpoint(s) that answer eth_simulateV1; \
             failover cannot help if the only one that can simulate is down",
            profile.simulate_endpoints
        );
    }
}

#[test]
fn simulation_counts_never_exceed_the_endpoints_they_count() {
    for profile in known_networks() {
        let endpoints = profile.config.rpc_urls.len();
        assert!(
            profile.simulate_endpoints <= endpoints && profile.fork_endpoints <= endpoints,
            "chain {} claims more simulating endpoints than it lists",
            profile.config.chain_id
        );
    }
}

#[test]
fn lookups_agree_with_the_list() {
    let profile = known_network(1).expect("Ethereum is in the registry");
    assert_eq!(profile.config.chain_id, 1);
    assert!(known_network(u64::MAX).is_none());
}

#[test]
fn a_registry_entry_without_endpoints_is_refused() {
    let error = parse(
        r#"{"chains":[{"chain_id":1,"name":"ethereum","display_name":"Ethereum","aliases":[],
            "default":true,"testnet":false,"native_currency":null,"max_gas_limit":null,
            "block_explorer_url":null,"documentation_url":null,"simulate_endpoints":0,
            "fork_endpoints":0,"rpc_urls":[]}]}"#,
    )
    .expect_err("a chain with no endpoint is not a network");
    assert!(
        format!("{error:#}").contains("at least one RPC URL"),
        "unexpected error: {error:#}"
    );
}
